// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.shmoula.ukazbobra.domain;

import cz.shmoula.ukazbobra.domain.ImageDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ImageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ImageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ImageIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ImageIntegrationTest: @Transactional;
    
    @Autowired
    private ImageDataOnDemand ImageIntegrationTest.dod;
    
    @Test
    public void ImageIntegrationTest.testCountImages() {
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        long count = cz.shmoula.ukazbobra.domain.Image.countImages();
        org.junit.Assert.assertTrue("Counter for 'Image' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ImageIntegrationTest.testFindImage() {
        cz.shmoula.ukazbobra.domain.Image obj = dod.getRandomImage();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = cz.shmoula.ukazbobra.domain.Image.findImage(id);
        org.junit.Assert.assertNotNull("Find method for 'Image' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Image' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ImageIntegrationTest.testFindAllImages() {
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        long count = cz.shmoula.ukazbobra.domain.Image.countImages();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Image', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<cz.shmoula.ukazbobra.domain.Image> result = cz.shmoula.ukazbobra.domain.Image.findAllImages();
        org.junit.Assert.assertNotNull("Find all method for 'Image' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Image' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ImageIntegrationTest.testFindImageEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        long count = cz.shmoula.ukazbobra.domain.Image.countImages();
        if (count > 20) count = 20;
        java.util.List<cz.shmoula.ukazbobra.domain.Image> result = cz.shmoula.ukazbobra.domain.Image.findImageEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Image' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Image' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ImageIntegrationTest.testFlush() {
        cz.shmoula.ukazbobra.domain.Image obj = dod.getRandomImage();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = cz.shmoula.ukazbobra.domain.Image.findImage(id);
        org.junit.Assert.assertNotNull("Find method for 'Image' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyImage(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Image' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageIntegrationTest.testMerge() {
        cz.shmoula.ukazbobra.domain.Image obj = dod.getRandomImage();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = cz.shmoula.ukazbobra.domain.Image.findImage(id);
        boolean modified =  dod.modifyImage(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        cz.shmoula.ukazbobra.domain.Image merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Image' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", dod.getRandomImage());
        cz.shmoula.ukazbobra.domain.Image obj = dod.getNewTransientImage(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Image' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Image' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ImageIntegrationTest.testRemove() {
        cz.shmoula.ukazbobra.domain.Image obj = dod.getRandomImage();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Image' failed to provide an identifier", id);
        obj = cz.shmoula.ukazbobra.domain.Image.findImage(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Image' with identifier '" + id + "'", cz.shmoula.ukazbobra.domain.Image.findImage(id));
    }
    
}
